const notesModel = require('./notesModel')
const NotesView = require('./NotesView.js')
const NotesClient = require('./NotesClient')
model = new notesModel()
client = new NotesClient()
view = new NotesView(model, client)
console.log(view.displayNotesFromApi())
// View.displayNotes()
// console.log(model.getNotes())
// console.log("The note app is running")